### PR TITLE
Ping every 30 seconds to keep the connection alive

### PR DESCRIPTION
**Pull request by bkeepers**
https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses

It works!

```
curl -H 'Accept: text/event-stream'  https://smee.io/omg                                        

id: 0
event: ready
data: {}

id: 1
event: ping
data: {}

id: 2
event: ping
data: {}

id: 3
event: ping
data: {}
```

### CODE REVIEW

**Comment by bkeepers** [comment]
Good suggestion. I refactored it (and maybe slightly overengineered it) to reset the interval whenever a message is sent

**Comment by tcbyrd** [comment]
This is awesome and is working from the command line, but for `webhooks.html` (the React app), I see two issues:

- No way to see connection status
- It's seen as a separate client to the server, so if I see an event on the command line and then want to look at it in more detail on the web server, the event isn't there and it would have to be redelivered from the GitHub UI.

Thoughts on how to solve? I notice the events have IDs on the CLI. Is there a way for one client to see the events sent to another? Or do we just need store the events somehow using the channel name?

**Comment by JasonEtco** [comment]
> No way to see connection status

💯 - I noted that [here](https://github.com/probot/webhooks/pull/18#pullrequestreview-82319386) as well, just haven't had a chance to get around to it.

> It's seen as a separate client to the server, so if I see an event on the command line and then want to look at it in more detail on the web server, the event isn't there and it would have to be redelivered from the GitHub UI.

I'm not quite sure what you mean - are you saying the the ping should show up in the browser?

**Comment by tcbyrd** [comment]
> I'm not quite sure what you mean - are you saying the the ping should show up in the browser?

Not necessarily, but if you don't have the browser open while working from the command line, then you open the channel in the browser, it doesn't show the events that were recently sent to the command line client. If you send an event with both clients connected, you'll see them in both places, but if only one is connected, only that one receives the message.

**Comment by bkeepers** [comment]
> …it doesn't show the events that were recently sent to the command line client

Yeah, we'll work on adding persistence at some point. I think we can just use Redis to store the last ~x events (20-50) for each channel for ~2 days.

**Pull request merged**
